In [1]:
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Test case 1 
processes = ['P0', 'P1', 'P2','P3']
arrival_time = [0,0,0,0]
burst_time = [4,2,1,3]
waiting_time = [0,4,6,7]
turnaround_time = [4,6,7,10]
complete_time = [4,6,7,10]

In [3]:
# test case 2
processes = ['P0', 'P1', 'P2','P3','P4']
arrival_time = [0,1,2,3,7]
burst_time = [3,2,1,1,1]
waiting_time = [0,2,3,3,0]
turnaround_time = [3,4,4,4,1]
complete_time = [3,5,6,7,8]

In [4]:
# test case 3
processes = ['A', 'B', 'C','D','E']
arrival_time = [0,0,2,3,1]
burst_time = [3,2,1,4,3]
waiting_time = [0,3,6,6,4]
turnaround_time = [3,5,7,10,7]
complete_time = [3,5,9,13,8]

In [5]:
# test case 4 - todo: check all the values
processes = ['P1','P2','P3','P4','P5','P6']
arrival_time = [0,25,30,60,100,105]
burst_time = [20,25,25,15,10,10]
waiting_time = [0,0,20,15,0,5]
turnaround_time = [20,25,45,30,10,15]
complete_time = [20,50,75,90,110,120]

In [6]:
expected_answer = pd.DataFrame({'Process':processes, 'Arrival Time':arrival_time, 'Burst Time':burst_time, 
                               'Waiting Time':waiting_time, 'Turn Around Time':turnaround_time, 'Completion Time':complete_time})
expected_answer.sort_values(by=['Arrival Time', 'Burst Time'], ignore_index=True, inplace=True)

In [7]:
def sort_process_fcfs(processes, arrival_time, burst_time):
    """
    Sort the process based on arrival time and burst time
    """
    # create a list of tuple (process, arrival time, burst time)
    process_list = [(process, arrival, burst) for process, arrival, burst in zip(processes, arrival_time, burst_time)]
    
    # sort the list based on arrival time
    process_list.sort(key=lambda x: (x[1], x[0], x[2]))
    # process_list.sort(key=lambda x: x[1])
    print("Sorted Processed List", process_list)
    
    # return the sorted list
    return process_list

In [8]:
def fcfs(processes, arrival_time, burst_time):
    sorted_processes=sort_process_fcfs(processes, arrival_time, burst_time)
    df = pd.DataFrame(sorted_processes, columns=[ 'Process', 'Arrival Time', 'Burst Time'])
    
    n = len(df)
    
    df['Waiting Time'] = 0
    df['Turn Around Time'] = 0
    df['Completion Time'] = 0
    
    df['Turn Around Time'].iloc[0] = df['Burst Time'].iloc[0] + df['Waiting Time'].iloc[0]
    df['Completion Time'].iloc[0] = df['Burst Time'].iloc[0] + df['Arrival Time'].iloc[0]
    
    for i in range(1, n):
        if df['Arrival Time'].iloc[i] > df['Completion Time'].iloc[i-1]:
            df['Completion Time'].iloc[i] = df['Arrival Time'].iloc[i] + df['Burst Time'].iloc[i]
        else:
            df['Completion Time'].iloc[i] = df['Burst Time'].iloc[i] + df['Completion Time'].iloc[i-1]
            
        df['Waiting Time'].iloc[i] = max(0, df['Completion Time'].iloc[i-1] - df['Arrival Time'].iloc[i])
        df['Turn Around Time'].iloc[i] = df['Burst Time'].iloc[i] + df['Waiting Time'].iloc[i]
    
        
    df = df[['Process', 'Arrival Time', 'Burst Time', 'Waiting Time', 'Turn Around Time', 'Completion Time']]
        
    print("\nProcess Details:")
    for i in range(n):
        print(f"Process: {df['Process'].iloc[i]}, Wait Time: {df['Waiting Time'].iloc[i]}, Turn Around Time: {df['Turn Around Time'].iloc[i]}, Completion Time: {df['Completion Time'].iloc[i]}")
        
    print(f"\nAverage Waiting Time: {df['Waiting Time'].mean():.2f} ")
    print(f"Average Turn Around Time:  {df['Turn Around Time'].mean():.2f} ")
    return df.reset_index(drop=True)

In [9]:
actual_answer = fcfs(processes, arrival_time, burst_time)

Sorted Processed List [('P1', 0, 20), ('P2', 25, 25), ('P3', 30, 25), ('P4', 60, 15), ('P5', 100, 10), ('P6', 105, 10)]

Process Details:
Process: P1, Wait Time: 0, Turn Around Time: 20, Completion Time: 20
Process: P2, Wait Time: 0, Turn Around Time: 25, Completion Time: 50
Process: P3, Wait Time: 20, Turn Around Time: 45, Completion Time: 75
Process: P4, Wait Time: 15, Turn Around Time: 30, Completion Time: 90
Process: P5, Wait Time: 0, Turn Around Time: 10, Completion Time: 110
Process: P6, Wait Time: 5, Turn Around Time: 15, Completion Time: 120

Average Waiting Time: 6.67
Average Turn Around Time:  24.17

In [10]:
actual_answer

,Process,Arrival Time,Burst Time,Waiting Time,Turn Around Time,Completion Time
0,P1,0,20,0,20,20
1,P2,25,25,0,25,50
2,P3,30,25,20,45,75
3,P4,60,15,15,30,90
4,P5,100,10,0,10,110
5,P6,105,10,5,15,120

In [11]:
check_actual_answer = actual_answer.sort_values(by=['Arrival Time', 'Burst Time'], ignore_index=True)

In [12]:
check_actual_answer

,Process,Arrival Time,Burst Time,Waiting Time,Turn Around Time,Completion Time
0,P1,0,20,0,20,20
1,P2,25,25,0,25,50
2,P3,30,25,20,45,75
3,P4,60,15,15,30,90
4,P5,100,10,0,10,110
5,P6,105,10,5,15,120

In [13]:
expected_answer

,Process,Arrival Time,Burst Time,Waiting Time,Turn Around Time,Completion Time
0,P1,0,20,0,20,20
1,P2,25,25,0,25,50
2,P3,30,25,20,45,75
3,P4,60,15,15,30,90
4,P5,100,10,0,10,110
5,P6,105,10,5,15,120

In [14]:
diff = check_actual_answer.compare(expected_answer)

if diff.empty:
    print("Your answer is correct")
else:
    print("Your answer is incorrect")
    
diff

Your answer is correct

Empty DataFrame
Columns: []
Index: []

In [15]:
from pandas.testing import assert_frame_equal
assert_frame_equal(check_actual_answer, expected_answer)